### PR TITLE
50 add pytests

### PR DESCRIPTION
**Pull request by baileywickham**
This adds support for pytests which test some basic functionality of our app. We test creating a user, creating a contact, and updating a contact. This should allow us to more quickly make changes and verify they are working correctly.

### CODE REVIEW

**Review by AlexMaclean — CHANGES_REQUESTED** [review]
I think this is a great start to testing the functioning of our database, but there are a few things I think should change before we merge it in.

While our database is largely agnostic when it comes to the content within a contact that it is storing, it's still a little weird to be testing creating and editing contacts with contacts that could never actually exist. I think it might be a good idea to update these to reflect the API specs doc.

I also think the tests could maybe benefit from a few more asserts. For example in `test_create_contact` you never check that `c` contains the data in `_c`. In addition, `test_update_contact` should probably make another contact and make sure that it remains untouched.

Also, I know this may seem a little pedantic, but we're following the PEP 8 style guide and the [white-space guidelines](https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements) specify that there shouldn't be white-space before a ":". So you should update the creation of `_c` to reflect that.

**Comment by baileywickham** [comment]
> I think this is a great start to testing the functioning of our database, but there are a few things I think should change before we merge it in.
> 
> While our database is largely agnostic when it comes to the content within a contact that it is storing, it's still a little weird to be testing creating and editing contacts with contacts that could never actually exist. I think it might be a good idea to update these to reflect the API specs doc.
> 
> I also think the tests could maybe benefit from a few more asserts. For example in `test_create_contact` you never check that `c` contains the data in `_c`. In addition, `test_update_contact` should probably make another contact and make sure that it remains untouched.
> 
> Also, I know this may seem a little pedantic, but we're following the PEP 8 style guide and the [white-space guidelines](https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements) specify that there shouldn't be white-space before a ":". So you should update the creation of `_c` to reflect that.

The code now conforms to PEP8. Ideally, this could be handled in the CI server in the future.  

When using ==, python implicitly assumes the __eq__ method is the same as that of dictionaries, so it compares all attributes of the objects. c == _c would fail if any of the data was different. 

I added an additional test to create two different contacts and check that they have both properly been inserted and are different in the database. This should address your and third comment.

**Review by ysunkara — APPROVED** [review]
Looks good to me as long

**Review by AlexMaclean — APPROVED** [review]
Thanks for making these changes. I think the code is ready to be merged in.

**Comment by cprghunter** [comment]
Looks good to me after Alex's requested changes.

**Pull request merged**
